"""empty message

Revision ID: 00dc53b010e9
Revises: 
Create Date: 2022-03-03 00:50:58.918238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dc53b010e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_Name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('class_grade', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_grade'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('guardian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('seats_available', sa.Integer(), nullable=True),
    sa.Column('payment_info', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('black_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blacklisted_guardian_id', sa.Integer(), nullable=True),
    sa.Column('blacklisting_guardian_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blacklisted_guardian_id'], ['guardian.id'], ),
    sa.ForeignKeyConstraint(['blacklisting_guardian_id'], ['guardian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_to_guardian',
    sa.Column('guardian_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], )
    )
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flagged_guardian', sa.Integer(), nullable=True),
    sa.Column('flag_creator', sa.Integer(), nullable=True),
    sa.Column('flag_comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['flag_creator'], ['guardian.id'], ),
    sa.ForeignKeyConstraint(['flagged_guardian'], ['guardian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('school_address', sa.String(length=255), nullable=False),
    sa.Column('school_logo_url', sa.String(length=255), nullable=False),
    sa.Column('active_complaints', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_complaints'], ['complaint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_name')
    )
    op.create_table('school__access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('is_driver', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('morning', sa.Boolean(), nullable=True),
    sa.Column('afternoon', sa.Boolean(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wedenesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school__access')
    op.drop_table('school')
    op.drop_table('complaint')
    op.drop_table('child_to_guardian')
    op.drop_table('black_list')
    op.drop_table('guardian')
    op.drop_table('user')
    op.drop_table('child')
    # ### end Alembic commands ###
