"""empty message

Revision ID: 1107cf605ac8
Revises: c3029c9b393f
Create Date: 2022-05-13 16:18:47.488626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1107cf605ac8'
down_revision = 'c3029c9b393f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_request', sa.Column('requested_school_id', sa.Integer(), nullable=True))
    op.drop_constraint('ride_request_requested_school_fkey', 'ride_request', type_='foreignkey')
    op.create_foreign_key(None, 'ride_request', 'school', ['requested_school_id'], ['id'])
    op.drop_column('ride_request', 'requested_school')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_request', sa.Column('requested_school', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ride_request', type_='foreignkey')
    op.create_foreign_key('ride_request_requested_school_fkey', 'ride_request', 'school', ['requested_school'], ['id'])
    op.drop_column('ride_request', 'requested_school_id')
    # ### end Alembic commands ###
