"""empty message

Revision ID: a9e8c589d80a
Revises: d4768afd4a8b
Create Date: 2022-05-08 05:37:34.891989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e8c589d80a'
down_revision = 'd4768afd4a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'child', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'child', type_='foreignkey')
    op.drop_column('child', 'school_id')
    # ### end Alembic commands ###
