"""empty message

Revision ID: c3029c9b393f
Revises: a9e8c589d80a
Create Date: 2022-05-13 06:52:18.672439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3029c9b393f'
down_revision = 'a9e8c589d80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requesting_guardian_id', sa.Integer(), nullable=False),
    sa.Column('accepting_guardian_id', sa.Integer(), nullable=True),
    sa.Column('requested_day', sa.String(length=255), nullable=False),
    sa.Column('requested_seats', sa.Integer(), nullable=False),
    sa.Column('requested_time', sa.String(length=255), nullable=False),
    sa.Column('requested_school', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepting_guardian_id'], ['guardian.id'], ),
    sa.ForeignKeyConstraint(['requested_school'], ['school.id'], ),
    sa.ForeignKeyConstraint(['requesting_guardian_id'], ['guardian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ride_request')
    # ### end Alembic commands ###
