"""empty message

Revision ID: ce8c383f0e2e
Revises: 324fdb32d84f
Create Date: 2022-03-18 20:48:07.023571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8c383f0e2e'
down_revision = '324fdb32d84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('age', sa.String(length=255), nullable=False))
    op.drop_constraint('child_phone_key', 'child', type_='unique')
    op.drop_column('child', 'phone')
    op.drop_column('child', 'gender')
    op.add_column('school', sa.Column('school_phone', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'school', ['school_phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school', type_='unique')
    op.drop_column('school', 'school_phone')
    op.add_column('child', sa.Column('gender', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('child_phone_key', 'child', ['phone'])
    op.drop_column('child', 'age')
    # ### end Alembic commands ###
